### ISSUE TITLE
Compile- / Install- instructions / Makefile

### ISSUE THREAD

**Issue by klartext** [ContentMine/norma#11]
IMHO it woule make sense to add a Makefile that makes compilation and installation easy.
The typical usage
make
make install
would make sense.

Maybe also ./configure stuff (auto-tools); but just some ENV-variables for configuration of the compile/install would be enough, I think.

**Comment by petermr** [comment]
Thanks,
`norma` and `ami-plugin` and written in Java, which uses Maven to build the
system. Maven is effectively `make` for Java and deals with the multiple
dependencies and platform-independence (which `make` does not do). So it's
the best and the most  appropriate tool for the job.

The typical installation command is:
`mvn clean install`
and this does everything that
`make clean`
would do in a C/++ compile/link.

The system is also built through rigorous "continuous integration" which is
run at
`jenkins.ch.cam.ac.uk`
every time new code in the system is committed. AMI/norma is complex and
involves about 10-20 upstream libraries. It's the dependency management
which is the main challenge and Jenkins makes sure that it only builds when
this is fully correct.

It you are happy with simply *running* (rather than *building*) the system,
then Jenkins exposes the *.jar and the *.deb files which can be run without
building.




On Sun, Aug 23, 2015 at 3:38 PM, klartext <notifications@github.com> wrote:

> IMHO it woule make sense to add a Makefile that makes compilation and
> installation easy.
> The typical usage
> make
> make install
> would make sense.
>
> Maybe also ./configure stuff (auto-tools); but just some ENV-variables for
> configuration of the compile/install would be enough, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContentMine/norma/issues/11>.
>



-- 
Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by klartext** [comment]
I would be happy with just installing and using, yes.
But AFAIK there is no such way; but if an
Arch-package would be provided, that would be nice,
and make things easy.
